project_id = "urkftxznsynmvkskytih"

[functions.apply-decor]
verify_jwt = false

[functions.creative-chat]
verify_jwt = false

[functions.generate-magazine-captions]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.get-users-admin]
verify_jwt = false